name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  dockerize:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:dev .
        docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:dev

  deploy-container:
    runs-on: ubuntu-latest
    needs: dockerize
    steps:
    - name: Update Container in the Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP_ADDRESS }}
        username: ${{ secrets.SERVER_DEPLOYMENT_USER }}
        key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
        port: ${{ secrets.SERVER_SSH_PORT }}
        script: |
          docker pull ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:dev
          docker stop client_dev || true
          docker rm client_dev || true
          docker run -d -p 8304:8304 --name client_dev ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:dev
          docker image prune -f || true